trigger:
- main

pool:
  name: ubuntu-latest
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: npm install 
  displayName: 'npm install'
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/sampleTest'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: npx playwright test
  displayName: 'Run Playwright tests'
  env:
    CI: 'true'